export default {
    FETCH_PARSED_DATA_REQUEST: null,
    FETCH_PARSED_DATA_SUCCESS: null,
    FETCH_PARSED_DATA_FAILURE: null,

    UPDATE_PARSED_DATA_SUCCESS: null,
    UPDATE_PARSED_DATA_FAILURE: null,

    UPDATE_MARKDOWN_HTML_DATA: null
};
